### ISSUE TITLE
Anime list is laggy

### ISSUE THREAD

**Issue by Methosss** [ValerioLyndon/Theme-Customiser#62]
### Has this question been asked already?

- [X] I have searched the existing issues and this is a new question.

### What did you want to know/discuss?

How to optimize anime list? it's possible to load site every 50 titles?

**Comment by ValerioLyndon** [comment]
MyAnimeList is the one that controls how many items load at once, which is 300. We can't change that.

What we can control is the lag. You should always aim for the list to be responsive at first load, if it isn't then you need to reconsider how many addons you are putting on your list. Lag is highly dependent on which design you installed and what mods you enabled, so if your list is slow then you should consider dialing it back. Flashier visuals and extra features generally see a 1:1 increase in required power. 

Looking at your animelist you have some heavy visuals and addons, including the cover image mod which warns that it will slow down the page. Here's some recommendations to try and reduce the lag, in order of how much they should make a difference:

1. Remove the mangalist cover import (found around line 12 of your CSS). This is adding an extra ~8mb of page load to your animelist solely for the convenience of having the same theme across anime and manga, so you should remove it:
```
@\import "https://malscraper.azurewebsites.net/covers/manga/Methosu/presets/dataimagelinkbefore";
```
If you use the mangalist and want the covers, then you should use a second list style on MAL and do the inverse on that one: keeping the manga import and removing the anime line.

2. Optimise your cover image. Currently you are using a [1.35MB PNG image](https://cdn.discordapp.com/attachments/816846657202683906/1187554359173718087/1534364394-bf607a9c4213719b2d08b990c9eae6b2.png). Large images will slow load times and in extreme cases can lag the browser. I would recommend converting it to JPG or webp at a quality you find acceptable so that the output is around 500-600kb. If you don't know how, use [ezgif](https://ezgif.com/png-to-jpg). Optimising the avatar wouldn't hurt either by resizing it to 150x150 pixels and/or converting to JPG. 

3. As a last resort, try disabling the "Transparent List Rows" mod. You can do this manually by finding and deleting lines ~37-50. It is marked with code comments.

If the lag still seems above normal levels after that you can let me know, but as I say there is a certain amount of extra processing power required with the flashy effects like transparency, large images, and more. The large/HD cover image mods are some of the heaviest modifications, at least in the way of added network load from the CSS and larger images.
